---
version: '2'
services:
  worker:
    build: .
    volumes:
      - "./data:/data"
    environment:
      - LOG_GROUP_PREFIX
      - LOGENTRIES_TOKEN
      - NAMESPACE
      - STATSD_HOST
      - STATSD_PORT
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
