---
steps:
  - name: ":docker: :construction:"
    command: "bin/ci build"
    agents:
      queue: build

  - wait

  - name: ":docker: :label:"
    command: "bin/ci tag staging"
    branches: master

  - wait

  - name: ":buildkite: :shipit: :suspect:"
    command: "bin/deploy courier"
    env:
      CONVOX_RACK: staging
      LOG_GROUP_PREFIX: staging-
      STATSD_HOST: statsd.staging.internal
      STATSD_PORT: 8125
      LOGENTRIES_TOKEN: ""
      AWS_DEFAULT_REGION: ""
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""

  - wait

  - name: ":docker: :label:"
    command: "bin/ci tag production"
    branches: master

  - wait

  - name: ":buildkite: :shipit: :feelsgood:"
    command: "bin/deploy courier"
    branches: master
    env:
      CONVOX_RACK: production
      LOG_GROUP_PREFIX: production-
      STATSD_HOST: statsd.production.internal
      STATSD_PORT: 8125
      LOGENTRIES_TOKEN: ""
      AWS_DEFAULT_REGION: ""
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
