---
steps:
  - name: ":docker: :construction:"
    command: "bin/ci build"
    agents:
      queue: build

  - wait

  - name: ":docker: :label:"
    command: "bin/ci tag staging"
    branches: master

  - wait

  - name: ":buildkite: :shipit:"
    command: "plain-utils deploy-convox courier-staging -e tag=$COMMIT"
    branches: master

